resources:
- name: repo
  type: git
  source:
    uri: https://github.com/sgdan/docker-utils.git
    branch: master

- name: docker
  type: docker-image
  source:
    repository: docker
    tag: 18.09

- name: docker-utils-image
  type: docker-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/docker-utils

jobs:
- name: publish
  plan:
  - get: repo
  - get: docker
    params: {save: true}
  - put: docker-utils-image
    params:
      load_base: docker
      build: repo
